### ISSUE TITLE
Cannot resolve module 'ReactPullLoad'

### ISSUE THREAD

**Issue by GZWZC** [react-ld/react-pullLoad#1]
after i npm install react-pullload, in my js, i import the ReactPullLoad , webpack warm tips "Cannot resolve module 'ReactPullLoad'"

**Comment by lidianhao123** [comment]
Do you add  below code ？
```js
import ReactPullLoad from 'react-pullload'
```

**Comment by lidianhao123** [comment]
@GZWZC I will close this issue, if you get the same tips or any other bug(issue) please reopen this issue. By the way, react-pullload version 1.0.4 is released now. I wish you can try it.

**Comment by GZWZC** [comment]
ok, thanks you
