### ISSUE TITLE
demo安装不了

### ISSUE THREAD

**Issue by xzk821649509** [react-ld/react-pullLoad#10]
![tim 20180424151717](https://user-images.githubusercontent.com/28725954/39171868-9dcbbd3e-47d2-11e8-9d46-80c9bd80f96d.png)
如图

**Comment by xzk821649509** [comment]
作者是你将下载权限关闭了吗

**Comment by lidianhao123** [comment]
@xzk821649509 gulp-gh-pages 这个包有问题，如果你不需要发布到 github gh-pages 分支可以暂时去掉这个依赖包
