### ISSUE TITLE
请问 我不重写head和footer，是不是有默认的？

### ISSUE THREAD

**Issue by git-Asir** [react-ld/react-pullLoad#11]
我看demo1，您的代码里没有特别加headnode和footernode，但是展示时候有头部和尾部显示文字，但是我在集成时候，写的却没有这部分东西，还有回到顶部需要设置什么，引一些依赖包之类的么？我的一直不起作用，还有get到的值一直是0
![image](https://user-images.githubusercontent.com/26689535/40595208-d931cfc8-6265-11e8-9378-300754ec57ba.png)

![image](https://user-images.githubusercontent.com/26689535/40595346-97e3ba12-6266-11e8-9588-d16fda33478b.png)
刚刚接触react，有好多东西不太熟悉，还在学习，请大佬帮忙看看...

**Comment by lidianhao123** [comment]
根据描述无法判断问题出在哪里，建议提供一个可复现的代码，我来check一下

**Comment by git-Asir** [comment]
@lidianhao123 请问 isBlockContainer这个字段怎么理解？

**Comment by git-Asir** [comment]
@lidianhao123 找到问题了，没有引入样式表，.pull-load 这些都没有，我的锅

**Comment by lidianhao123** [comment]
已解决
