### ISSUE TITLE
建议将下拉刷新时候的下移距离做成可设置的

### ISSUE THREAD

**Issue by laden666666** [react-ld/react-pullLoad#2]
现在这个距离是3rem，建议控件不要用rem作单位，因为独立的第三方控件不应该依赖于(限制住)使用者的html的字体大小，如果使用者设置了很大或者很小的html的font-size，控件在刷新的时候就会变得十分诡异。
建议使用vh这种相对单位，或者可以让用户手动配置

**Comment by lidianhao123** [comment]
感谢您的建议，我会尽快优化

**Comment by laden666666** [comment]
挺不错的控件，感觉比好多老外写的都好，但是还有一些可以改进的地方，比如提示语也可以配置。现在都是用css的before或者after什么的，理论是通过设置css也可以配置这些信息，但是总不如用props配置来得容易。还有一点就是文档，里面一些属性描述的不是很清楚，比如应该补充如果设置了isBlockContainer=true的时候，需要给ReactPullLoad设置高度和overflow-y: auto，否则会出现列表无法上移的bug，我是看过源码后才弄明白isBlockContainer的使用方法，应该在文档中给出足够的描述

**Comment by lidianhao123** [comment]
组件更新至1.0.4，3rem问题和提示语问题都已经解决。新版本API进行了变更，详情请查看 Readmd 接口说明或者参考 demo
