### ISSUE TITLE
加入侧滑删除功能是否与组件功能冲突？

### ISSUE THREAD

**Issue by walkinMrwang** [react-ld/react-pullLoad#3]
建议将em换为rem，大v的组件表示很好用，在项目中使用hoc进行封装了。谢谢开源

**Comment by lidianhao123** [comment]
1. 关于em转为rem问题，默认UI 组件 HeadNode 和 FooterNode 暂时不考虑修改样式相关的代码。如果与实际项目有不相符的话，建议使用自定义HeadNode 和 FooterNode。参考[demo3](https://github.com/react-ld/react-pullLoad)  [demo3 源码](https://github.com/react-ld/react-pullLoad/blob/master/demo/App2.jsx#L15)
2. 加入侧滑删除功能是否与组件功能冲突，这个目前我重新 review 一下代码，react-pullLoad 组件只会处理垂直方向的位移大于水平位移的情况 [code](https://github.com/react-ld/react-pullLoad/blob/master/src/ReactPullLoad.jsx#L194)；侧滑删除需求的条件是水平位移大于垂直位移应该可以正常。当然实现侧滑删除时也要确保不满足侧滑情况下触摸事件的正常传递（事件冒泡流）。

以上，感谢对本组件的支持。

**Comment by lidianhao123** [comment]
@walkinMrwang 我将关闭该问题，如果还未解决的话请留言
