### ISSUE TITLE
我想自定义些方法，从dist中取出，出现如下报错

### ISSUE THREAD

**Issue by walkinMrwang** [react-ld/react-pullLoad#4]
Line 94:  Unexpected use of 'screen'  no-restricted-globals

**Comment by lidianhao123** [comment]
您好，dist 路径下是我对demo代码编译打包后输出的，不能直接使用。如果要修改源码，增加方法的话直接在src中对于的文件中编辑。或者提供详细的需求描述，我看看能否帮助到您。

感谢对本组件的支持！

**Comment by lidianhao123** [comment]
@walkinMrwang 
```shell
Line 94: Unexpected use of 'screen' no-restricted-globals
```
最近在使用 ESLint 发现，这个应该是 ESLint 的提示，可以通过配置 ESLint 的全局配置进行解决请参考 [Disallow specific global variables (no-restricted-globals)](https://eslint.org/docs/rules/no-restricted-globals)

我将关闭此问题，后续还有问题的话欢迎提交 issue
