### ISSUE TITLE
在滚动条往下滑了以后,再往上滑直接出发了更新状态,导致无法往上滑动

### ISSUE THREAD

**Issue by cxylys** [react-ld/react-pullLoad#5]
![image](https://user-images.githubusercontent.com/3087711/32432210-a85ef7b6-c311-11e7-9eef-35ae9c260df8.png)
在我往下滑动内容了一些后,再往上滑却触发了 下拉刷新的动作, 正常应该是到了顶部才会触发.所以不太明白会是什么原因导致的。

**Comment by lidianhao123** [comment]
能否提供更详细的说明，可重现的例子或者具体使用代码。

**Comment by lidianhao123** [comment]
请检查一下 isBlockContainer 的配置，如果是 true 的话使用组件根 DOM 作为外部容器。此时请配置组件跟DOM元素的高度并且设置超出后滚动的样式。style="overflow-y:scroll;"

**Comment by cxylys** [comment]
目前我的isBlockContainer 配置是默认值false的,比如我在当前页浏览往下滑动
![image](https://user-images.githubusercontent.com/3087711/32484970-a831895e-c3dc-11e7-8aa8-782f8981f4a0.png)
![image](https://user-images.githubusercontent.com/3087711/32485005-c792bd22-c3dc-11e7-8908-09478055e3e6.png)
当我再想往上滑动的时候直接触发到了
![image](https://user-images.githubusercontent.com/3087711/32485040-eb19ea0e-c3dc-11e7-9cab-0015364cc0aa.png)这个状态,貌似是当前react-pullLoad容易的滚动条导致的.

**Comment by cxylys** [comment]
现在这上面的demo也有这个问题, 原来在用的时候倒没有。

**Comment by lidianhao123** [comment]
你是用的 [demo3](https://react-ld.github.io/react-pullLoad/index3.html) 在新版本 chrome 上面测试出现的这个问题吧，可以试试手机端应该没有问题。

chrome 上面是因为如下原因引起的，暂时还没有规划好如何修改该问题。
```shell
bundle3.js:18 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

**Comment by cxylys** [comment]
这个我也发现了,在手机往上滑是不会触发refresh的, 但是 加载更多的阈值没用了,设到1000 都要到底部以后 再拉一下 才能触发加载。
![image](https://user-images.githubusercontent.com/3087711/32538804-49974d2c-c4a2-11e7-88e1-3478c39a319c.png)
如果是根据body滚动条加载的话,body应该是不需要设置高度的才对,我再多试试吧。谢谢的回答。

**Comment by lidianhao123** [comment]
该问题已经解决，先关闭此问题了

**Comment by gluckMu** [comment]
这个问题是在什么时候修复的，我现在使用的是npm上的1.0.8版本，但是还是会出现这种问题

**Comment by cxylys** [comment]
这个问题没有修复的吧,在Pc端还是会有这问题，只是在移动端不会,但是在移动端 根据body 滚动触发的话load数据不太好触发了,得拉倒底部再拉一下才会触发Load状态,原来阈值设大一点 滑动不到底部就可以触发了。不知道你再移动端是否有这个问题。

**Comment by lidianhao123** [comment]
@gluckMu 您的问题是PC 新版本 chrome 上面测试出现的这个问题吗？或者是其他情况下的问题，受累提供一下详细描述。

PC 新版本 chrome 的问题，会在近期进行修复。

@cxylys 关于移动端加载更多内容的问题，跟您在确认一下问题的描述。
问题描述：设置很大的阈值也需要拉到底部再拉一下才能触发加载更多？是这样吗？

**Comment by cxylys** [comment]
对的, 在移动端是到了底部 还需要在底部再上拉一下才会触发load。我在pc端试过在Body 加overflow-y:scroll  后新版的chrome 上下拉都不会有问题,而且再pc端体验load 也不会有问题, 但是在body 加了overflow-y:scroll后 在移动端 会出现pc新版chrome 的问题 无法往上滑

**Comment by gluckMu** [comment]
@lidianhao123 我是在qq浏览器上测试的，内核Chromium 45.0.2454.85，我测试demo2和demo3都没有问题，但是我自己在写的时候就是出现了往上拉时候立即触发刷新，移动端也是这样，难道是我写错了，生成的dom结构如下图
![aaa](https://user-images.githubusercontent.com/6963867/33068714-19bd176c-ceed-11e7-9d25-93c327df07c7.png)

**Comment by cxylys** [comment]
我不太清楚是不是因为这个组件的版本问题, 我最早开始使用的时候pc,移动端都是好的,后来chrome升级后发现了在chrome下拉时立即触发刷新的问题（期间我重新在npm 重新安装过react-pullLoad）,此时移动端的load 阈值也没用了,必须在移动端底部在触发上拉才可以,而且升级过后的pc chrome无法触发load 了,

**Comment by lidianhao123** [comment]
@cxylys @gluckMu 邀请帮忙测试一下修改后的demo是否正常，地址[gh-pages](https://github.com/react-ld/react-pullLoad/tree/gh-pages) demo1 - demo4

如果没有问题的话我将发布新版本。感谢支持！

**Comment by cxylys** [comment]
我今天在我手机,PC上试了一下倒是可以了,不过还是拉倒底部才加载的,可能是你阈值设得比较低吧, 今天用同事安卓机上测现在版本的居然没有问题。-。-

**Comment by lidianhao123** [comment]
@cxylys 请问使用的 demo 几测试的需要拉到底部才加载（另外是PC端吗）？

**Comment by cxylys** [comment]
这个可能是加载的元素较少,我拉一下就到底部了。你可以发个测试版本我重新安装下在我应用里跑跑。

**Comment by cxylys** [comment]
另外提个建议是刷新完成闭合时的动画是否可以圆滑一点,现在的这个动画感觉像是卡回去的,https://lidianhao123.github.io/pullLoad/  这个demo的动画有比现在demo的动画平滑很多

**Comment by lidianhao123** [comment]
@cxylys 
1、请使用新版本1.0.9 已经发布，请在实际项目中试用（期待您的反馈）。
2、闭合动画作为组件优化功能，之后会考虑是否增加。

**Comment by shaohaojun** [comment]
这个还能评论吗？发现确实有这个问题（第一次可以正常下拉刷新，和加载更多。但是当加载更多时候，再想往上看第一页的内容，没办法往上看（下滑），一下滑就自动重新刷新了，只有当上滑时候加载更多手指不离屏幕，才可以流畅点的下滑，看到以前的一部分内容）。开始还以为代码写错了，后来发现这个评论区。一直看demo3那个没问题，为什么自己写的代码就有问题呢？IOS,安卓都有这个问题。我试过1.1.0版本和1.2.0版本，当用1.0.0版本的时候HeadNode.js报一个错误。
