### ISSUE TITLE
如何将下拉刷新禁止掉

### ISSUE THREAD

**Issue by Notdefind** [react-ld/react-pullLoad#6]
有些页面不需要下拉刷新， 每次获取数据都会从调出下拉的动画 有什么方法将下拉刷新禁止掉

**Comment by Notdefind** [comment]
![image](https://user-images.githubusercontent.com/17826565/32541878-921ff560-c436-11e7-9bd2-f89849ae9c88.png)
如图

**Comment by lidianhao123** [comment]
@Notdefind 抱歉，当天我就回复这个问题了，可是刚刚发现当时忘记提交了。

关于每次获取数据都会从调出下拉动画，这个问题请从具体业务角度再看一下，应该和使用组件没有关系。获取数据后直接设置数据即可，react 代码如下：

```js
//this.state.data 是用于渲染展示的数据，fetchData 是获取来的数据
this.setState({data: fetchData});
```


另外单独需要禁用下拉刷新功能的请参考我新增加的[示例代码](https://github.com/react-ld/react-pullLoad/blob/master/demo/App3.jsx#L40)

**Comment by Notdefind** [comment]
谢谢，已解决此问题。

**Comment by cxylys** [comment]
禁用下拉刷新的示例怎么404了? 麻烦再提供一下示例

**Comment by lidianhao123** [comment]
@cxylys 
[demo](https://react-ld.github.io/react-pullLoad/index4.html)
[示例代码](https://github.com/react-ld/react-pullLoad/blob/master/example/App4.jsx#L40)
```js
  handleAction = (action) => {
    console.info(action, this.state.action,action === this.state.action);
    // loading 以外的状态都不处理
    if(action !== STATS.loading){
      return false;
    }
    ...
  }
```
