### ISSUE TITLE
是否可以开放一个滚动监听事件

### ISSUE THREAD

**Issue by ano0822** [react-ld/react-pullLoad#8]
当滚动条滚动时可以获取到滚动的距离，在列表情况下，滚动一段距离后进入子页面，在返回到页面上是定位不到之前滚动的地方

**Comment by lidianhao123** [comment]
问题已经解决？React 单页应用返回之前页面记录滚动位置，需要看你的具体使用的什么路由组件。如果使用的 react-router V4 请参考[scroll-restoration](https://reacttraining.com/react-router/web/guides/scroll-restoration)
