### ISSUE TITLE
能否使用RN的FlatList或者ListView API重新更新一下

### ISSUE THREAD

**Issue by Mad-hu** [react-ld/react-pullLoad#9]
能否使用RN的FlatList或者ListView API重新更新一下使用方法，这样我就能够将RN的代码原封不动的在web上使用了。

**Comment by Mad-hu** [comment]
还有就是 现在proptypes这个需要更新一下， 不然在新的项目中会报错。
![image](https://user-images.githubusercontent.com/13977755/35550868-6264ebaa-05c7-11e8-8b42-722104cad6d4.png)

**Comment by Mad-hu** [comment]
import React, { PureComponent, PropTypes } from 'react'

**Comment by lidianhao123** [comment]
@Mad-hu 
1. RN 本人没有开发经验，暂时无法支持该需求的添加。
2. PropTypes 报错问题是因为 React 16.0 移除React.PropTypes支持，本项目会尽快更新新版本来支持 React ^16.0 版本。

**Comment by Mad-hu** [comment]
@lidianhao123  非常感谢，能够这么快的更新，Rn的这个我自己封装了一下，可以用了，还有一个问题，就是当页面滚动到下方的时候，再想下拉回顶部，这个时候下拉会出发刷新。不知道你有没有发现这个问题。
![das](https://user-images.githubusercontent.com/13977755/35609120-071c9ea2-0697-11e8-8fbb-fb776f85d458.gif)

**Comment by lidianhao123** [comment]
@Mad-hu 
react-pullLoad 版本号？测试环境？在相同环境下试试 [demo1](https://react-ld.github.io/react-pullLoad/index1.html) 看是否重现该问题。

**Comment by Mad-hu** [comment]
"react-pullload": "^1.0.9",

**Comment by Mad-hu** [comment]
@lidianhao123  突然好了，具体咋回事也是不清楚  ……

**Comment by lidianhao123** [comment]
@Mad-hu 解决就好，能否给出错误代码例子，我好添加到说明文档中。感谢支持！

**Comment by Mad-hu** [comment]
代码挺难往出抽的，我做了个图，你看看

![10_](https://user-images.githubusercontent.com/13977755/35712872-55062084-07ff-11e8-8fe0-68b283c6f157.gif)

**Comment by depyuka** [comment]
react 16能不能尽快支持一下啊,先解决兼容性问题

**Comment by Mad-hu** [comment]
@depyuka 先手动node_module里边改一下吧，我暂时是这么做的

**Comment by lidianhao123** [comment]
@Mad-hu @depyuka 已经升级到1.1.0版本支持 React 16
